version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.1
    working_directory: /go/src/test
    steps:
    - checkout
    - run: go build
workflows:
  version: 2
  workflow:
    jobs:
    - build